twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [
        'bootstrap_4_layout.html.twig',
        'bootstrap_4_horizontal_layout.html.twig',
        'bootstrap_5_layout.html.twig',
        'bootstrap_5_horizontal_layout.html.twig'
    ]
